name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # ğŸ”¥ Firebase (runtime only)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8

  # State & routing
  provider: ^6.1.2
  go_router: ^17.0.1

  # Utils
  shared_preferences: ^2.2.2
  http: ^1.2.0
  url_launcher: ^6.2.5
  image_picker: ^1.0.7

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
